name: Build and Publish CV

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Just
      uses: taiki-e/install-action@v2
      with:
        tool: just

    - name: Log in to the Container registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build PDFs using Just
      run: just

    - name: Push image to GHCR
      run: podman push ghcr.io/aetf/cv:latest
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    - name: Upload CV Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cv-pdf
        path: build/cv.pdf

    - name: Upload Resume Artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf
        path: build/resume.pdf

    - name: Create/Update Release
      uses: softprops/action-gh-release@v2
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      with:
        tag_name: latest
        name: Latest Continuous Build
        body: Automated build from latest commit.
        files: |
          build/cv.pdf
          build/resume.pdf
        prerelease: true
